# Generated by Django 5.0.6 on 2024-08-19 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_customuser_profile_picture_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Très mauvais'), (2, '2 - Mauvais'), (3, '3 - Moyen'), (4, '4 - Bon'), (5, '5 - Excellent')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
